config/routes.rb
Rails.application.routes.draw do
  resources :pages
  get '/static/:permalink', to: 'pages#permalink', as: 'permalink'

  resources :game, only: [:index, :show]
  resources :developer, only: [:index, :show]
  resources :publisher, only: [:index, :show]
  resources :platform, only: [:index, :show]
  resources :genre, only: [:index, :show]

  get 'game/show'
  get 'game/index'
  get 'developer/show'
  get 'developer/index'
  get 'publisher/show'
  get 'publisher/index'
  get 'genre/show'
  get 'genre/index'
  get 'platform/show'
  get 'platform/index'

  root to: 'game#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :games
  has_many :sales

end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :genre
  belongs_to :publisher
  belongs_to :developer
  belongs_to :platform

  validates :game_name, :year_of_release, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games
  has_many :sales

  validates :genre_name, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :games
  has_many :sales

  validates :platform_name, presence: true
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :games
  has_many :sales
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :game
  belongs_to :developer
  belongs_to :publisher
  belongs_to :genre
  belongs_to :platform

  validates :game_rank, :na_sales, :jp_sales, :global_sales, presence: true
  validates :na_sales, :jp_sales, :global_sales, numericality: { only_decimal: true }
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    @games = Game.order(:game_rank).page params[:page]
  end

  def show
    @games = Game.find(params[:id])
  end

  def search_results
    @query = params[:query]
    @games = Game.where('name LIKE ?' , '%#{@query}%')
  end
end

app/controllers/genre_controller.rb
class GenreController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
  end

  def index
    @genre = Genre.order(:developer_name).page params[:page]
  end

  def search_results
    @query = params[:query]
    @genre = Genre.where('name LIKE ?' , '%#{@query}%')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  http_basic_authenticate_with name: "games", password: "voodoo_secrets"
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def permalink
    @page = Page.find_by_permalink(params[:permalink])

    if @page
      render :show
    else
      redirect_to root_path
    end
  end

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:title, :context, :permalink)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developer_helper.rb
module DeveloperHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/platform_helper.rb
module PlatformHelper
end

app/helpers/publisher_helper.rb
module PublisherHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoGamesSales</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-xl navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/">Video Game Sales</a>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Games</a>
          </li>
          <li class="nav-item "">
            <a class=" nav-link" href="/developer">Developers</a>
          </li>
          <li class="nav-item "">
            <a class=" nav-link" href="/publisher">Publishers</a>
          </li>
          <li class="nav-item "">
            <a class=" nav-link" href="/genre ">Genres</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/platform">Platforms</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/pages">About us</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0" action="/search" accept-charset="UTF-8" method="get"><input name="utf8"
            type="hidden" value="&#x2713;" />
          <input type="text" name="q" id="q" class="form-control mr-sm-2" placeholder="Game Search" />
          <input type="submit" name="commit" value="Search" class="btn btn-outline-success my-2 my-sm-0"
            data-disable-with="Search" />
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :context %>
    <%= form.text_area :context %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Context</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.context %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @page.title %>
</h1>

<p>
  <%= @page.context %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>